### ISSUE TITLE
transparent proxying, bind error

### ISSUE THREAD

**Issue by jesseklm** [yrutschle/sslh#64]
I'm using Debian 7.8 and sslh-select v1.17.
My `sslh.cfg`:

```
listen:
(
    { host: "0.0.0.0"; port: "443"; }
);
protocols:
(
     { name: "ssh"; service: "ssh"; host: "192.168.0.1"; port: "222"; probe: "builtin"; },
     { name: "ssl"; host: "192.168.0.1"; port: "4443"; probe: "builtin"; }
);
```

Transparent proxying is working fine, except for one situation.
I tunnel via ssh on port 443 and try to open `https://192.168.0.1:443`.
I'm getting `ERR_CONNECTION_CLOSED` and sslh is writing in `auth.log`:

```
bind:98:Address already in use
bind_peer:98:Address already in use
```

I can open `https://192.168.0.1:4443` successfully.

**Comment by yrutschle** [comment]
On Tue, Sep 01, 2015 at 04:43:23AM -0700, jesseklm wrote:
> I tunnel via ssh on port 443 and try to open `https://192.168.0.1:443`.

I am not sure what you mean here:
ssh -L 443:localhost:443 -p 443 example.org

or something else?

**Comment by jesseklm** [comment]
Thank you for your fast answer!
I mean something like:
```
ssh -N -D localhost:9870 example.org
```
using Firefox with a socks5-proxy at `localhost:9870`

**Comment by ViKingIX** [comment]
In the transparent proxy mode, sslh will bind a virtual socket with the destination address. But when the destination and the source are the same machine, the bind_peer() function will fail because the socket is physically there. I created a pull request to fix problem.

**Comment by yrutschle** [comment]
I assume this is solved.

**Comment by neersighted** [comment]
#69 has not been merged yet.

**Comment by pochy-ja** [comment]
I still have the same error with centos 7 and systemd, sslh-1.18-1.el7

Jul 10 15:56:35 example.com sslh[3634]: ssh addr: localhost.localdomain:ssh. libwrap service: (null) log_level: 1 family 2 2 []
Jul 10 15:56:35 example.com sslh[3634]: listening on:
Jul 10 15:56:35 example.com sslh[3634]: example.com:snpp        []
Jul 10 15:56:35 example.com sslh[3634]: timeout: 2
Jul 10 15:56:35 example.com sslh[3634]: on-timeout: ssh
Jul 10 15:56:35 example.com sslh[3634]: listening to 1 addresses
Jul 10 15:56:35 example.com sslh[3634]: example.com:snpp:bind: Address already in use
Jul 10 15:56:35 example.com systemd[1]: sslh.service: main process exited, code=exited, status=1/FAILURE
Jul 10 15:56:35 example.com systemd[1]: Unit sslh.service entered failed state.
Jul 10 15:56:35 example.com systemd[1]: sslh.service failed.

Note: example.com domain was replaced for the real domain.

**Comment by yrutschle** [comment]
On Sun, Jul 10, 2016 at 01:07:35PM -0700, Juan Antonio Aguilera Tamayo wrote:
> Jul 10 15:56:35 example.com sslh[3634]: example.com:snpp:bind: Address already in use

Something is already listning on the snpp port (whatever
that is, and whatever reason you're making sslh listen on
that port :-) ).

netstat -lpt 

will list listening processes.

Y.

**Comment by pochy-ja** [comment]
As I see, the responsible of this port is sslh, see the log

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 localhost.localdo:10025 0.0.0.0:*               LISTEN      904/master          
tcp        0      0 0.0.0.0:mysql           0.0.0.0:*               LISTEN      1080/mysqld         
tcp        0      0 0.0.0.0:pop3            0.0.0.0:*               LISTEN      681/dovecot         
tcp        0      0 0.0.0.0:imap            0.0.0.0:*               LISTEN      681/dovecot         
tcp        0      0 example.com:domain    0.0.0.0:*               LISTEN      856/named           
tcp        0      0 localhost.locald:domain 0.0.0.0:*               LISTEN      856/named           
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN      622/sshd            
tcp        0      0 0.0.0.0:smtp            0.0.0.0:*               LISTEN      904/master          
tcp        0      0 localhost.localdom:rndc 0.0.0.0:*               LISTEN      856/named           
tcp        0      0 localhost.localdo:https 0.0.0.0:*               LISTEN      936/httpd           
tcp        0      0 example.com:snpp      0.0.0.0:*               LISTEN      2022/sslh           
tcp        0      0 0.0.0.0:sieve           0.0.0.0:*               LISTEN      681/dovecot         
tcp6       0      0 [::]:http               [::]:*                  LISTEN      936/httpd           
tcp6       0      0 [::]:ftp                [::]:*                  LISTEN      1159/proftpd: (acce 
tcp6       0      0 [::]:domain             [::]:*                  LISTEN      856/named           
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      622/sshd            
tcp6       0      0 [::]:smtp               [::]:*                  LISTEN      904/master

**Comment by yrutschle** [comment]
On Mon, Jul 11, 2016 at 02:58:39PM -0700, Juan Antonio Aguilera Tamayo wrote:
> As I see, the responsible of this port is sslh, see the log


Erm, maybe you need to kill old sslh's that are laying
around?

There might also be an issue when the server is on both IPv4
and IPv6, and sslh binds on both at once but they're
specified twice (or something like that, I don't remember
the specifics). So it's worth trying to specify the IPv4 and
IPv6 listen addresses separately and explicitely to see if
that helps.

(I have no IPv6 on my server at the moment, so I'm a bit
removed from those issues).

**Comment by pochy-ja** [comment]
> Erm, maybe you need to kill old sslh's that are laying around?

It does not work.

> So it's worth trying to specify the IPv4 and IPv6 listen addresses separately and explicitely to see if that helps

How can I do this in the /etc/sslh.cfg?

BTW, I have another server with ipv4 and ipv6 and with the same config, sslh works fine, but the server have Centos 6, Centos 7 is the problem, Do you think that is related with systemd issue?

**Comment by pochy-ja** [comment]
HI @yrutschle any news about this problem?, you continue without IPv6 in your server for test this?

**Comment by yrutschle** [comment]
Nothing new: as long as netstat says there is an sslh listening on port 2022, it won't be able to listen again on that port and you won't be able to start a new one.

Or I don't understand the problem, please explain again assuming no prior posts :-)

**Comment by pochy-ja** [comment]
OK, last night I tried this

/usr/sbin/sslh -p 0.0.0.0:445 --ssh localhost:22 --ssl localhost:443 --user nobody --pidfile /var/run/sslh.pid

And is works, but this only works for IPv4, the problem is related with the service by default(/etc/sslh.cfg) try to execute for the two interface(IPv4 and IPv6).

**Comment by yrutschle** [comment]
Closing due to sedimentation. If the issue still exist, please create a new issue describing the problem from scratch.
